# Generated by Django 5.0.7 on 2025-10-18 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('physical', 'Physical Development'), ('cognitive', 'Cognitive Development'), ('social', 'Social & Emotional'), ('language', 'Language & Communication'), ('motor', 'Motor Skills')], max_length=20)),
                ('typical_age_weeks', models.PositiveIntegerField(help_text='Typical age in weeks when milestone is reached')),
                ('age_range_start', models.PositiveIntegerField(help_text='Earliest typical age in weeks')),
                ('age_range_end', models.PositiveIntegerField(help_text='Latest typical age in weeks')),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['typical_age_weeks'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('recommended_age_weeks', models.PositiveIntegerField(help_text='Recommended age in weeks')),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['recommended_age_weeks'],
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birth_date', models.DateField()),
                ('birth_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('birth_height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='baby_photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Babies',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='DiaperRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('diaper_type', models.CharField(choices=[('wet', 'Wet'), ('dirty', 'Dirty'), ('both', 'Both'), ('dry', 'Dry')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaper_records', to='babytracker.baby')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('feeding_type', models.CharField(choices=[('breastfeeding', 'Breastfeeding'), ('bottle', 'Bottle'), ('solid', 'Solid Food'), ('mixed', 'Mixed')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration in minutes (for breastfeeding)', null=True)),
                ('amount_ml', models.PositiveIntegerField(blank=True, help_text='Amount in ml (for bottle feeding)', null=True)),
                ('food_description', models.TextField(blank=True, help_text='Description of solid food')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='babytracker.baby')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='1-5 scale', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to='babytracker.baby')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, help_text='Head circumference in cm', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='babytracker.baby')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('baby', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BabyMilestoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achieved', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='milestone_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_records', to='babytracker.baby')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babytracker.milestone')),
            ],
            options={
                'ordering': ['-date_achieved'],
                'unique_together': {('baby', 'milestone')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField()),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('clinic_name', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='babytracker.baby')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babytracker.vaccination')),
            ],
            options={
                'ordering': ['-date_given'],
                'unique_together': {('baby', 'vaccination')},
            },
        ),
    ]
