# Generated by Django 5.2.8 on 2025-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Medical diagnosis'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_instructions',
            field=models.TextField(blank=True, help_text='Follow-up care instructions'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.TextField(blank=True, help_text='Prescribed medications'),
        ),
    ]
